# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('facility', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('is_student', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='studens',
        ),
        migrations.AddField(
            model_name='work_for_competition',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.competition'),
        ),
        migrations.AddField(
            model_name='work_for_competition',
            name='work_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.work'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED')], default='RUNNING', max_length=9),
        ),
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.profile'),
        ),
        migrations.AlterField(
            model_name='work_for_competition',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.profile'),
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='competition',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='part', to='Course.profile'),
        ),
    ]
